@inject IUserApiClient UserApiClient
@inject IExceptionHandler ExceptionHandler

<EditForm Model="Command" OnValidSubmit="HandleValidSubmit">
    <CustomValidator @ref="CustomValidator" />
    <FluentValidationValidator />

    <MudDialog DefaultFocus="DefaultFocus.LastChild">
        <DialogContent>
            <MudTextField Label="Email" @bind-Value="Command.Email" For="() => Command.Email" />
            <ValidationMessage For="() => Command.Email" />

            <MudTextField Label="UserName" @bind-Value="Command.UserName" For="() => Command.UserName" />
            <ValidationMessage For="() => Command.UserName" />

            <PasswordField Label="Password" @bind-Value="Command.Password" For="() => Command.Password" />
            <ValidationMessage For="() => Command.Password" />

            <PasswordField Label="Repeat Password" @bind-Value="Command.RepeatPassword" For="() => Command.RepeatPassword" />
            <ValidationMessage For="() => Command.RepeatPassword" />
        </DialogContent>
        <DialogActions>
            <MudButton ButtonType="ButtonType.Submit" Color="Color.Primary" Disabled="_processing">
                @if (_processing)
                {
                    <MudProgressCircular Size="Size.Small" Indeterminate="true" />
                    <MudText>Processing...</MudText>
                }
                else
                {
                    <MudText Typo="Typo.subtitle2">REGISTER</MudText>
                }
            </MudButton>
        </DialogActions>
    </MudDialog>
</EditForm>

@code {
    [CascadingParameter] public MudDialogInstance MudDialog { get; set; }
    [Parameter] public Register.Command Command { get; set; } = new();

    private CustomValidator CustomValidator = new();
    private bool _processing;

    private async Task HandleValidSubmit()
    {
        _processing = true;

        try
        {
            await UserApiClient.Register(Command);
            MudDialog.Close(DialogResult.Ok(true));
        }
        catch (MyValidationException validationException)
        {
            CustomValidator.DisplayErrors(validationException.Errors);
        }
        catch (Exception ex)
        {
            ExceptionHandler.HandleExceptions(ex);
        }

        _processing = false;
    }
}
